service: client-mini-hack-api

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  memorySize: 128
  timeout: 5
  environment:
    DESTINATION: ${file(./config.json):DESTINATION}
    REPLY_TO: ${file(./config.json):REPLY_TO}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
      - 'ses:SendEmail'
      Resource: '*'

package:
  exclude:
    - '**/*.ts'
    - '*'
  include:
    - 'src/**/*.js'
    - 'src/**/*.ejs'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  email:
    description: 'Email API'
    handler: src/lambda.api
    events:
      - http: ANY /
      - http: ANY /{proxy+}
